repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff
        language: system
        types: [python]
        args: ["check", "--fix"]
        exclude: ^tests/
      - id: ruff-format
        name: ruff-format
        entry: ruff
        language: system
        types: [python]
        args: ["format"]
        exclude: ^tests/
      - id: mypy
        name: mypy
        entry: C:/Users/Administrator/CodeInsightAi/codeinsight-backend/.venv/Scripts/mypy.exe
        language: system
        types: [python]
        pass_filenames: true
        args: ["--ignore-missing-imports"]
        exclude: ^tests/
