repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff
        language: system
        types: [python]
        args: ["check", "--fix"]
        files: ^codeinsight-backend/codeinsight/
      - id: ruff-format
        name: ruff-format
        entry: ruff
        language: system
        types: [python]
        args: ["format"]
        files: ^codeinsight-backend/codeinsight/
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ["--ignore-missing-imports", "codeinsight-backend/codeinsight/"]
        files: ^codeinsight-backend/codeinsight/
        always_run: true
