/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Repositories
         * @description 获取仓库列表
         *
         *     分页返回用户的所有仓库。
         */
        get: operations["list_repositories_api_v1_repositories_get"];
        put?: never;
        /**
         * Create Repository
         * @description 添加代码仓库
         *
         *     添加一个新的代码仓库并开始分析。
         */
        post: operations["create_repository_api_v1_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repository
         * @description 获取仓库详情
         */
        get: operations["get_repository_api_v1_repositories__repository_id__get"];
        /**
         * Update Repository
         * @description 更新仓库信息
         */
        put: operations["update_repository_api_v1_repositories__repository_id__put"];
        post?: never;
        /**
         * Delete Repository
         * @description 删除仓库及其所有分析数据
         */
        delete: operations["delete_repository_api_v1_repositories__repository_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Analysis
         * @description 提交分析任务
         */
        post: operations["submit_analysis_api_v1_repositories__repository_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Status
         * @description 查询任务状态
         */
        get: operations["get_task_status_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Task
         * @description 取消分析任务
         */
        post: operations["cancel_task_api_v1_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Knowledge Points
         * @description 获取知识点列表
         */
        get: operations["list_knowledge_points_api_v1_knowledge_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-points/{point_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge Point
         * @description 获取知识点详情
         */
        get: operations["get_knowledge_point_api_v1_knowledge_points__point_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/knowledge-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge Stats
         * @description 获取知识点统计
         */
        get: operations["get_knowledge_stats_api_v1_repositories__repository_id__knowledge_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description 搜索知识点
         */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Suggestions
         * @description 获取搜索建议
         */
        get: operations["search_suggestions_api_v1_search_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description 获取分析版本列表
         */
        get: operations["list_versions_api_v1_repositories__repository_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/switch-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Version
         * @description 切换到指定版本
         */
        post: operations["switch_version_api_v1_repositories__repository_id__switch_version_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rollback Version
         * @description 回滚到指定版本
         */
        post: operations["rollback_version_api_v1_repositories__repository_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 健康检查端点
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisMode
         * @description 分析模式
         * @enum {string}
         */
        AnalysisMode: "full" | "incremental";
        /**
         * AnalysisProgress
         * @description 分析进度信息
         */
        AnalysisProgress: {
            currentStep: components["schemas"]["TaskStatus"];
            /** Percent */
            percent: number;
            /** Filesprocessed */
            filesProcessed: number;
            /** Filestotal */
            filesTotal: number;
            /** Knowledgepointsfound */
            knowledgePointsFound: number;
        };
        /**
         * AnalysisTask
         * @description 分析任务
         */
        AnalysisTask: {
            /** Taskid */
            taskId: string;
            /** Repositoryid */
            repositoryId: string;
            status: components["schemas"]["TaskStatus"];
            mode: components["schemas"]["AnalysisMode"];
            progress: components["schemas"]["AnalysisProgress"];
            /** Submittedat */
            submittedAt: string;
            /** Startedat */
            startedAt?: string | null;
            /** Completedat */
            completedAt?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
        };
        /**
         * AnalysisVersion
         * @description 分析版本
         */
        AnalysisVersion: {
            /** Version */
            version: string;
            status: components["schemas"]["TaskStatus"];
            /** Totalfiles */
            totalFiles: number;
            /** Knowledgepointscount */
            knowledgePointsCount: number;
            /** Iscurrent */
            isCurrent: boolean;
            /** Createdat */
            createdAt: string;
            /** Completedat */
            completedAt?: string | null;
        };
        /**
         * AnalyzeRequest
         * @description 提交分析任务请求
         */
        AnalyzeRequest: {
            mode?: components["schemas"]["AnalysisMode"] | null;
            /** Agents */
            agents?: ("design_pattern" | "architecture" | "algorithm" | "engineering_tips" | "domain_knowledge")[] | null;
        };
        /**
         * CallChainNode
         * @description 调用链节点
         */
        CallChainNode: {
            /** Nodeid */
            nodeId: string;
            /**
             * Nodetype
             * @enum {string}
             */
            nodeType: "function" | "class" | "method" | "function_call" | "import" | "module";
            /** File */
            file: string;
            /** Lines */
            lines: [
                number,
                number
            ];
            /** Signature */
            signature: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "entry" | "call" | "implementation" | "export";
        };
        /**
         * CodeSnippet
         * @description 代码片段
         */
        CodeSnippet: {
            /** Filepath */
            filePath: string;
            /** Startline */
            startLine: number;
            /** Endline */
            endLine: number;
            /**
             * Highlightedlines
             * @default []
             */
            highlightedLines: number[];
            /** Language */
            language: string;
            /** Signature */
            signature: string;
        };
        /**
         * ExpansionContent
         * @description 拓展内容
         */
        ExpansionContent: {
            /** Principle */
            principle: string;
            /**
             * Applicablescenarios
             * @default []
             */
            applicableScenarios: string[];
            /**
             * Bestpractices
             * @default []
             */
            bestPractices: string[];
            /**
             * Relatedpatterns
             * @default []
             */
            relatedPatterns: string[];
            /**
             * Learningresources
             * @default []
             */
            learningResources: components["schemas"]["LearningResource"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KnowledgeCategory
         * @description 知识点分类枚举
         *
         *     DP-: 设计模式 (Design Pattern)
         *     AD-: 架构决策 (Architecture Decision)
         *     AL-: 算法实现 (Algorithm)
         *     ET-: 工程技巧 (Engineering Tip)
         *     DK-: 领域知识 (Domain Knowledge)
         * @enum {string}
         */
        KnowledgeCategory: "DP-" | "AD-" | "AL-" | "ET-" | "DK-";
        /**
         * KnowledgeMetadata
         * @description 知识点元数据
         */
        KnowledgeMetadata: {
            /** Agent */
            agent: string;
            /** Promptversion */
            promptVersion: string;
            /** Model */
            model: string;
            /**
             * Tokensused
             * @default {}
             */
            tokensUsed: {
                [key: string]: number;
            };
        };
        /**
         * KnowledgePoint
         * @description 知识点
         */
        KnowledgePoint: {
            /** Id */
            id: string;
            category: components["schemas"]["KnowledgeCategory"];
            /** Categoryname */
            categoryName: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Confidence */
            confidence: number;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Codesnippets
             * @default []
             */
            codeSnippets: components["schemas"]["CodeSnippet"][];
            /**
             * Callchain
             * @default []
             */
            callChain: components["schemas"]["CallChainNode"][];
            expansion: components["schemas"]["ExpansionContent"];
            /** Version */
            version: string;
            /** Repositoryid */
            repositoryId: string;
            metadata: components["schemas"]["KnowledgeMetadata"];
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
        /**
         * KnowledgeStats
         * @description 知识点统计
         */
        KnowledgeStats: {
            /** Totalpoints */
            totalPoints: number;
            /**
             * Bycategory
             * @default {}
             */
            byCategory: {
                [key: string]: number;
            };
            /**
             * Byconfidence
             * @default {}
             */
            byConfidence: {
                [key: string]: number;
            };
            /**
             * Toptags
             * @default []
             */
            topTags: {
                [key: string]: number;
            }[];
            /**
             * Filescovered
             * @default 0
             */
            filesCovered: number;
            /**
             * Totallinesanalyzed
             * @default 0
             */
            totalLinesAnalyzed: number;
        };
        /**
         * LearningResource
         * @description 学习资料
         */
        LearningResource: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /**
             * Type
             * @enum {string}
             */
            type: "book" | "article" | "video" | "course";
        };
        /**
         * Repository
         * @description 仓库信息
         */
        Repository: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            status: components["schemas"]["RepositoryStatus"];
            /** Currentversion */
            currentVersion?: string | null;
            /**
             * Filecount
             * @default 0
             */
            fileCount: number;
            /**
             * Linecount
             * @default 0
             */
            lineCount: number;
            /**
             * Knowledgepointscount
             * @default 0
             */
            knowledgePointsCount: number;
            /**
             * Languagedistribution
             * @default {}
             */
            languageDistribution: {
                [key: string]: number;
            };
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
            /** Lastanalyzedat */
            lastAnalyzedAt?: string | null;
        };
        /**
         * RepositoryCreate
         * @description 创建仓库请求
         */
        RepositoryCreate: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Autoanalyze */
            autoAnalyze?: boolean | null;
        };
        /**
         * RepositoryStatus
         * @description 仓库分析状态
         * @enum {string}
         */
        RepositoryStatus: "pending" | "analyzing" | "completed" | "failed" | "cancelled";
        /**
         * RepositoryUpdate
         * @description 更新仓库请求
         */
        RepositoryUpdate: {
            /** Name */
            name?: string | null;
        };
        /**
         * SearchMode
         * @description 搜索模式
         * @enum {string}
         */
        SearchMode: "text" | "vector" | "hybrid";
        /**
         * SearchRequest
         * @description 搜索请求参数
         */
        SearchRequest: {
            /** Q */
            q: string;
            /** Repositoryid */
            repositoryId?: string | null;
            /** Category */
            category?: string | null;
            mode?: components["schemas"]["SearchMode"] | null;
            /** Page */
            page?: number | null;
            /** Pagesize */
            pageSize?: number | null;
        };
        /**
         * SearchResponse
         * @description 搜索响应
         */
        SearchResponse: {
            /** Query */
            query: string;
            mode: components["schemas"]["SearchMode"];
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["SearchResult"][];
            /** Facets */
            facets?: {
                [key: string]: unknown;
            } | null;
            /**
             * Durationms
             * @default 0
             */
            durationMs: number;
        };
        /**
         * SearchResult
         * @description 搜索结果
         */
        SearchResult: {
            type: components["schemas"]["SearchResultType"];
            /** Score */
            score: number;
            /** Pointid */
            pointId?: string | null;
            /** Point */
            point?: {
                [key: string]: unknown;
            } | null;
            /** Repository */
            repository?: {
                [key: string]: unknown;
            } | null;
            /** Matchedtext */
            matchedText?: string | null;
        };
        /**
         * SearchResultType
         * @description 搜索结果类型
         * @enum {string}
         */
        SearchResultType: "knowledge_point" | "repository" | "file";
        /**
         * SearchSuggestion
         * @description 搜索建议
         */
        SearchSuggestion: {
            /** Text */
            text: string;
            /** Type */
            type: string;
            /** Count */
            count: number;
        };
        /**
         * SearchSuggestionsResponse
         * @description 搜索建议响应
         */
        SearchSuggestionsResponse: {
            /** Query */
            query: string;
            /**
             * Suggestions
             * @default []
             */
            suggestions: components["schemas"]["SearchSuggestion"][];
        };
        /**
         * TaskStatus
         * @description 分析任务状态
         * @enum {string}
         */
        TaskStatus: "pending" | "scanning" | "parsing" | "analyzing_modules" | "storing" | "completed" | "failed" | "cancelled";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_repositories_api_v1_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"][];
                };
            };
        };
    };
    create_repository_api_v1_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_api_v1_repositories__repository_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_repository_api_v1_repositories__repository_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_repository_api_v1_repositories__repository_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_analysis_api_v1_repositories__repository_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_v1_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_points_api_v1_knowledge_points_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePoint"][];
                };
            };
        };
    };
    get_knowledge_point_api_v1_knowledge_points__point_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                point_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePoint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_stats_api_v1_repositories__repository_id__knowledge_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_suggestions_api_v1_search_suggestions_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSuggestionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_repositories__repository_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_version_api_v1_repositories__repository_id__switch_version_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_version_api_v1_repositories__repository_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
