/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Repositories
         * @description 获取仓库列表
         *
         *     分页返回用户的所有仓库。
         */
        get: operations["list_repositories_api_v1_repositories_get"];
        put?: never;
        /**
         * Create Repository
         * @description 添加代码仓库
         *
         *     添加一个新的代码仓库，如果 auto_analyze 为 True 则自动提交分析任务。
         */
        post: operations["create_repository_api_v1_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repository
         * @description 获取仓库详情
         */
        get: operations["get_repository_api_v1_repositories__repository_id__get"];
        /**
         * Update Repository
         * @description 更新仓库信息
         */
        put: operations["update_repository_api_v1_repositories__repository_id__put"];
        post?: never;
        /**
         * Delete Repository
         * @description 删除仓库及其所有分析数据
         */
        delete: operations["delete_repository_api_v1_repositories__repository_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Analysis
         * @description 提交分析任务
         *
         *     创建一个异步分析任务并提交到 Celery 队列。
         *     返回 202 Accepted 状态码，表示任务已接受但尚未完成。
         */
        post: operations["submit_analysis_api_v1_repositories__repository_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Status
         * @description 查询任务状态
         *
         *     从 Celery result_backend 读取任务进度。
         *
         *     Args:
         *         task_id: Celery 任务 ID
         *
         *     Returns:
         *         AnalysisTask: 包含当前状态和进度的响应
         *
         *     Raises:
         *         HTTPException 404: 任务不存在或无法检索
         */
        get: operations["get_task_status_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Task
         * @description 取消分析任务
         *
         *     通过 Celery control.revoke 终止正在执行的 Worker 任务。
         *     如果任务已完成或不存在（eager 模式），返回相应提示。
         *
         *     Args:
         *         task_id: Celery 任务 ID
         *
         *     Returns:
         *         包含成功消息的字典
         *
         *     Raises:
         *         HTTPException 404: 任务不存在
         */
        post: operations["cancel_task_api_v1_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Knowledge Points
         * @description 获取知识点列表
         *
         *     分页返回指定仓库的知识点列表，支持按版本、分类、标签筛选。
         */
        get: operations["list_knowledge_points_api_v1_knowledge_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-points/{point_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge Point
         * @description 获取知识点详情
         *
         *     根据 ID 获取单个知识点的完整信息，包括代码片段、调用链、拓展内容等。
         */
        get: operations["get_knowledge_point_api_v1_knowledge_points__point_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/knowledge-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge Stats
         * @description 获取知识点统计
         *
         *     返回指定仓库的知识点统计数据，包括按分类分布、置信度分布、热门标签等。
         *     优化：9 次独立查询合并为 3 次（分类 GROUP BY + 总数 + 置信度 GROUP BY）。
         */
        get: operations["get_knowledge_stats_api_v1_repositories__repository_id__knowledge_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description 搜索知识点
         */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Suggestions
         * @description 获取搜索建议
         */
        get: operations["search_suggestions_api_v1_search_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description 获取分析版本列表
         *
         *     返回指定仓库的所有分析版本，按创建时间降序排列。
         */
        get: operations["list_versions_api_v1_repositories__repository_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/switch-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Version
         * @description 切换到指定版本
         *
         *     将仓库的当前版本设置为指定版本，后续查询将使用该版本的数据。
         *
         *     API-9 修复：只允许切换到已完成的版本，禁止切换到分析中或已失败的版本。
         */
        post: operations["switch_version_api_v1_repositories__repository_id__switch_version_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rollback Version
         * @description 回滚到指定版本
         *
         *     将仓库状态恢复到指定历史版本（语义上表示从当前版本撤回）。
         *
         *     API-13 修复：复用 _update_current_version 共享逻辑，消除重复代码。
         *     API-14 修复：移除伪造的 rollback_record_id。
         */
        post: operations["rollback_version_api_v1_repositories__repository_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description 获取文件列表（分页）
         */
        get: operations["list_files_api_v1_files_get"];
        put?: never;
        /**
         * Create File
         * @description 添加代码文件
         *
         *     在指定仓库下添加一个新文件。
         */
        post: operations["create_file_api_v1_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description 获取文件详情
         */
        get: operations["get_file_api_v1_files__file_id__get"];
        /**
         * Update File
         * @description 更新文件信息
         */
        put: operations["update_file_api_v1_files__file_id__put"];
        post?: never;
        /**
         * Delete File
         * @description 删除文件
         */
        delete: operations["delete_file_api_v1_files__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/by-hash/{content_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Files By Hash
         * @description 根据内容哈希查找文件（用于增量检测）
         */
        get: operations["get_files_by_hash_api_v1_files_by_hash__content_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ast-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ast Nodes
         * @description 获取 AST 节点列表
         *
         *     支持按文件、仓库、节点类型过滤。
         *     至少提供 file_id 或 repository_id 之一。
         */
        get: operations["list_ast_nodes_api_v1_ast_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ast-nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ast Node
         * @description 获取单个 AST 节点详情
         */
        get: operations["get_ast_node_api_v1_ast_nodes__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/call-edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Call Edges
         * @description 获取调用边列表
         *
         *     支持按文件、仓库、节点类型过滤。
         *     至少提供 file_id 或 repository_id 之一。
         */
        get: operations["list_call_edges_api_v1_call_edges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/call-edges/{node_id}/callees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Callees
         * @description 获取该节点调用的所有目标（正向调用图）
         *
         *     返回调用边列表，每条边包含 caller 和 callee 节点信息。
         *     callee 为 None 时表示该调用无法匹配到具体目标（未知调用）。
         */
        get: operations["get_callees_api_v1_call_edges__node_id__callees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/call-edges/{node_id}/callers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Callers
         * @description 获取调用该节点的所有调用者（反向调用图）
         *
         *     返回调用边列表，每条边包含 caller 节点信息。
         */
        get: operations["get_callers_api_v1_call_edges__node_id__callers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/call-edges/{node_id}/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Call Chain
         * @description 获取从该节点开始的完整调用链（DFS 遍历）
         *
         *     返回调用链节点列表，按深度排序。
         */
        get: operations["get_call_chain_api_v1_call_edges__node_id__chain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dependencies
         * @description 获取仓库的外部依赖列表
         *
         *     支持按生态系统和作用域过滤。
         */
        get: operations["list_dependencies_api_v1_repositories__repository_id__dependencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/dependencies/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count Dependencies
         * @description 获取仓库的外部依赖数量统计
         */
        get: operations["count_dependencies_api_v1_repositories__repository_id__dependencies_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/frameworks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Frameworks
         * @description 获取仓库检测到的框架列表
         *
         *     支持按类别和置信度过滤。
         */
        get: operations["list_frameworks_api_v1_repositories__repository_id__frameworks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/frameworks/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count Frameworks
         * @description 获取仓库检测到的框架数量统计
         */
        get: operations["count_frameworks_api_v1_repositories__repository_id__frameworks_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Routes
         * @description 获取仓库的 API 路由列表
         *
         *     支持按 HTTP 方法、框架、路径模式过滤。
         */
        get: operations["list_routes_api_v1_repositories__repository_id__routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/routes/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count Routes
         * @description 获取仓库的 API 路由数量统计
         */
        get: operations["count_routes_api_v1_repositories__repository_id__routes_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 健康检查端点
         *
         *     S-1 修复：不返回详细错误信息，避免泄露数据库连接信息等敏感数据。
         *     Q-1 修复：错误状态仅返回 "unavailable"，详细信息记录到日志。
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisMode
         * @description 分析模式
         * @enum {string}
         */
        AnalysisMode: "full" | "incremental";
        /**
         * AnalysisProgress
         * @description 分析进度信息
         */
        AnalysisProgress: {
            currentStep: components["schemas"]["TaskStatus"];
            /** Percent */
            percent: number;
            /** Filesprocessed */
            filesProcessed: number;
            /** Filestotal */
            filesTotal: number;
            /** Knowledgepointsfound */
            knowledgePointsFound: number;
        };
        /**
         * AnalysisTask
         * @description 分析任务
         */
        AnalysisTask: {
            /** Taskid */
            taskId: string;
            /** Repositoryid */
            repositoryId: string;
            status: components["schemas"]["TaskStatus"];
            mode: components["schemas"]["AnalysisMode"];
            progress: components["schemas"]["AnalysisProgress"];
            /** Submittedat */
            submittedAt: string | null;
            /** Startedat */
            startedAt?: string | null;
            /** Completedat */
            completedAt?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
        };
        /**
         * AnalysisVersion
         * @description 分析版本
         */
        AnalysisVersion: {
            /** Version */
            version: string;
            status: components["schemas"]["TaskStatus"];
            /** Totalfiles */
            totalFiles: number;
            /**
             * Analyzedfiles
             * @default 0
             */
            analyzedFiles: number;
            /** Knowledgepointscount */
            knowledgePointsCount: number;
            /** Iscurrent */
            isCurrent: boolean;
            /** Startedat */
            startedAt?: string | null;
            /** Completedat */
            completedAt?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
            /** Createdat */
            createdAt: string | null;
        };
        /**
         * AnalyzeRequest
         * @description 提交分析任务请求
         */
        AnalyzeRequest: {
            mode?: components["schemas"]["AnalysisMode"] | null;
            /** Agents */
            agents?: ("design_pattern" | "architecture" | "algorithm" | "engineering_tips" | "domain_knowledge")[] | null;
        };
        /**
         * ApiRoute
         * @description API 路由
         */
        ApiRoute: {
            /** Id */
            id: string;
            /** Repositoryid */
            repositoryId: string;
            /** Analysisversionid */
            analysisVersionId?: string;
            /** Astnodeid */
            astNodeId?: string;
            /** Httpmethod */
            httpMethod: string;
            /** Pathpattern */
            pathPattern: string;
            /** Handlerfunction */
            handlerFunction: string;
            /** Handlerfile */
            handlerFile: string;
            /**
             * Middlewares
             * @default []
             */
            middlewares: unknown[];
            /** Framework */
            framework: string;
            /** Createdat */
            createdAt: string;
        };
        /**
         * AstNode
         * @description AST 节点
         */
        AstNode: {
            /** Id */
            id: string;
            /** Repositoryid */
            repositoryId: string;
            /** Fileid */
            fileId: string;
            /** Nodetype */
            nodeType: string;
            /** Name */
            name: string;
            /** Startline */
            startLine: number;
            /** Endline */
            endLine: number;
            /**
             * Startcolumn
             * @default 0
             */
            startColumn: number;
            /**
             * Endcolumn
             * @default 0
             */
            endColumn: number;
            /** Parentnodeid */
            parentNodeId?: string;
            /** Filepath */
            filePath: string;
            /** Language */
            language: string;
            /** Signature */
            signature?: string | null;
            /** Docstring */
            docstring?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: unknown[];
            /**
             * Annotations
             * @default []
             */
            annotations: unknown[];
            /** Qualifiedname */
            qualifiedName?: string | null;
            /** Createdat */
            createdAt: string;
        };
        /**
         * CallChainNode
         * @description 调用链节点
         */
        CallChainNode: {
            /** Nodeid */
            nodeId: string;
            /**
             * Nodetype
             * @enum {string}
             */
            nodeType: "function" | "class" | "method" | "function_call" | "import" | "module";
            /** File */
            file: string;
            /** Lines */
            lines: [
                number,
                number
            ];
            /** Signature */
            signature: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "entry" | "call" | "implementation" | "export";
        };
        /**
         * CallEdge
         * @description 调用边
         */
        CallEdge: {
            /** Id */
            id: string;
            /** Repositoryid */
            repositoryId: string;
            /** Callernodeid */
            callerNodeId: string;
            /** Calleenodeid */
            calleeNodeId?: string;
            /** Startline */
            startLine: number;
            /** Startcolumn */
            startColumn: number;
            /** Callname */
            callName: string;
            /** Calltype */
            callType: string;
            /** Createdat */
            createdAt: string;
        };
        /**
         * CodeSnippet
         * @description 代码片段
         */
        CodeSnippet: {
            /** Filepath */
            filePath: string;
            /** Startline */
            startLine: number;
            /** Endline */
            endLine: number;
            /**
             * Highlightedlines
             * @default []
             */
            highlightedLines: number[];
            /** Language */
            language: string;
            /** Signature */
            signature: string;
        };
        /**
         * ExpansionContent
         * @description 拓展内容
         */
        ExpansionContent: {
            /** Principle */
            principle: string;
            /**
             * Applicablescenarios
             * @default []
             */
            applicableScenarios: string[];
            /**
             * Bestpractices
             * @default []
             */
            bestPractices: string[];
            /**
             * Relatedpatterns
             * @default []
             */
            relatedPatterns: string[];
            /**
             * Learningresources
             * @default []
             */
            learningResources: components["schemas"]["LearningResource"][];
        };
        /**
         * ExternalDependency
         * @description 外部依赖
         */
        ExternalDependency: {
            /** Id */
            id: string;
            /** Repositoryid */
            repositoryId: string;
            /** Analysisversionid */
            analysisVersionId?: string;
            /** Ecosystem */
            ecosystem: string;
            /** Groupname */
            groupName?: string | null;
            /** Artifactname */
            artifactName: string;
            /** Version */
            version?: string | null;
            /** Versionrange */
            versionRange?: string | null;
            /**
             * Scope
             * @default compile
             */
            scope: string;
            /** Declarationfile */
            declarationFile?: string | null;
            /**
             * Usedbyfiles
             * @default []
             */
            usedByFiles: unknown[];
            /** Createdat */
            createdAt: string;
        };
        /**
         * File
         * @description 代码文件
         */
        File: {
            /** Id */
            id: string;
            /** Repositoryid */
            repositoryId: string;
            /** Path */
            path: string;
            /** Absolutepath */
            absolutePath: string;
            /** Language */
            language: string;
            /** Linecount */
            lineCount: number;
            /** Sizebytes */
            sizeBytes: number;
            /** Contenthash */
            contentHash: string;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
        /**
         * FileCreate
         * @description 创建文件请求
         */
        FileCreate: {
            /** Path */
            path: string;
            /** Absolutepath */
            absolutePath: string;
            /** Language */
            language: string;
            /**
             * Linecount
             * @default 0
             */
            lineCount: number;
            /**
             * Sizebytes
             * @default 0
             */
            sizeBytes: number;
            /** Contenthash */
            contentHash: string;
        };
        /**
         * FileUpdate
         * @description 更新文件请求
         */
        FileUpdate: {
            /** Linecount */
            lineCount?: number | null;
            /** Sizebytes */
            sizeBytes?: number | null;
            /** Contenthash */
            contentHash?: string | null;
        };
        /**
         * FrameworkPattern
         * @description 框架模式
         */
        FrameworkPattern: {
            /** Id */
            id: string;
            /** Repositoryid */
            repositoryId: string;
            /** Analysisversionid */
            analysisVersionId?: string;
            /** Framework */
            framework: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /**
             * Evidence
             * @default {}
             */
            evidence: {
                [key: string]: unknown;
            };
            /** Detectedat */
            detectedAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KnowledgeCategory
         * @description 知识点分类枚举
         *
         *     DP-: 设计模式 (Design Pattern)
         *     AD-: 架构决策 (Architecture Decision)
         *     AL-: 算法实现 (Algorithm)
         *     ET-: 工程技巧 (Engineering Tip)
         *     DK-: 领域知识 (Domain Knowledge)
         * @enum {string}
         */
        KnowledgeCategory: "DP-" | "AD-" | "AL-" | "ET-" | "DK-";
        /**
         * KnowledgeMetadata
         * @description 知识点元数据
         */
        KnowledgeMetadata: {
            /** Agent */
            agent: string;
            /** Promptversion */
            promptVersion: string;
            /** Model */
            model: string;
            /**
             * Tokensused
             * @default {}
             */
            tokensUsed: {
                [key: string]: number;
            };
        };
        /**
         * KnowledgePoint
         * @description 知识点
         */
        KnowledgePoint: {
            /** Id */
            id: string;
            category: components["schemas"]["KnowledgeCategory"];
            /** Categoryname */
            categoryName: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Confidence */
            confidence: number;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Codesnippets
             * @default []
             */
            codeSnippets: components["schemas"]["CodeSnippet"][];
            /**
             * Callchain
             * @default []
             */
            callChain: components["schemas"]["CallChainNode"][];
            expansion: components["schemas"]["ExpansionContent"];
            /** Version */
            version: string;
            /** Repositoryid */
            repositoryId: string;
            /** Embedding */
            embedding?: number[] | null;
            metadata: components["schemas"]["KnowledgeMetadata"];
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
        /**
         * KnowledgeStats
         * @description 知识点统计
         */
        KnowledgeStats: {
            /** Totalpoints */
            totalPoints: number;
            /**
             * Bycategory
             * @default {}
             */
            byCategory: {
                [key: string]: number;
            };
            /**
             * Byconfidence
             * @default {}
             */
            byConfidence: {
                [key: string]: number;
            };
            /**
             * Toptags
             * @default []
             */
            topTags: {
                [key: string]: number;
            }[];
            /**
             * Filescovered
             * @default 0
             */
            filesCovered: number;
            /**
             * Totallinesanalyzed
             * @default 0
             */
            totalLinesAnalyzed: number;
        };
        /**
         * LearningResource
         * @description 学习资料
         */
        LearningResource: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /**
             * Type
             * @enum {string}
             */
            type: "book" | "article" | "video" | "course";
        };
        /**
         * PaginatedKnowledgePoints
         * @description 分页知识点列表响应
         */
        PaginatedKnowledgePoints: {
            /** Items */
            items: components["schemas"]["KnowledgePoint"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalpages */
            totalPages: number;
        };
        /**
         * Repository
         * @description 仓库信息
         */
        Repository: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            status: components["schemas"]["RepositoryStatus"];
            /** Currentversion */
            currentVersion?: string | null;
            /**
             * Filecount
             * @default 0
             */
            fileCount: number;
            /**
             * Linecount
             * @default 0
             */
            lineCount: number;
            /**
             * Knowledgepointscount
             * @default 0
             */
            knowledgePointsCount: number;
            /**
             * Languagedistribution
             * @default {}
             */
            languageDistribution: {
                [key: string]: number;
            };
            /** Createdat */
            createdAt: string | null;
            /** Updatedat */
            updatedAt: string | null;
            /** Lastanalyzedat */
            lastAnalyzedAt?: string | null;
        };
        /**
         * RepositoryCreate
         * @description 创建仓库请求
         */
        RepositoryCreate: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Autoanalyze */
            autoAnalyze?: boolean | null;
        };
        /**
         * RepositoryStatus
         * @description 仓库状态（M-3 修复：使用 StrEnum 替代松散 str，确保类型安全）
         *
         *     注意：analyzing_structures 是 TaskStatus 的细分状态，不在此枚举中。
         * @enum {string}
         */
        RepositoryStatus: "pending" | "analyzing" | "completed" | "failed" | "cancelled";
        /**
         * RepositoryUpdate
         * @description 更新仓库请求
         */
        RepositoryUpdate: {
            /** Name */
            name?: string | null;
            status?: components["schemas"]["RepositoryStatus"] | null;
        };
        /**
         * SearchMode
         * @description 搜索模式
         * @enum {string}
         */
        SearchMode: "text" | "vector" | "hybrid";
        /**
         * SearchRequest
         * @description 搜索请求参数
         */
        SearchRequest: {
            /** Q */
            q: string;
            /** Repositoryid */
            repositoryId?: string | null;
            /** Category */
            category?: string | null;
            mode?: components["schemas"]["SearchMode"] | null;
            /** Page */
            page?: number | null;
            /** Pagesize */
            pageSize?: number | null;
        };
        /**
         * SearchResponse
         * @description 搜索响应
         */
        SearchResponse: {
            /** Query */
            query: string;
            mode: components["schemas"]["SearchMode"];
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["SearchResult"][];
            /** Facets */
            facets?: {
                [key: string]: unknown;
            } | null;
            /**
             * Durationms
             * @default 0
             */
            durationMs: number;
        };
        /**
         * SearchResult
         * @description 搜索结果
         */
        SearchResult: {
            type: components["schemas"]["SearchResultType"];
            /** Score */
            score: number;
            /** Pointid */
            pointId?: string | null;
            /** Point */
            point?: {
                [key: string]: unknown;
            } | null;
            /** Repository */
            repository?: {
                [key: string]: unknown;
            } | null;
            /** Matchedtext */
            matchedText?: string | null;
        };
        /**
         * SearchResultType
         * @description 搜索结果类型
         * @enum {string}
         */
        SearchResultType: "knowledge_point" | "repository" | "file";
        /**
         * SearchSuggestion
         * @description 搜索建议
         */
        SearchSuggestion: {
            /** Text */
            text: string;
            /** Type */
            type: string;
            /** Count */
            count: number;
        };
        /**
         * SearchSuggestionsResponse
         * @description 搜索建议响应
         */
        SearchSuggestionsResponse: {
            /** Query */
            query: string;
            /**
             * Suggestions
             * @default []
             */
            suggestions: components["schemas"]["SearchSuggestion"][];
        };
        /**
         * TaskStatus
         * @description 分析任务状态
         * @enum {string}
         */
        TaskStatus: "pending" | "scanning" | "parsing" | "analyzing_structures" | "analyzing_modules" | "storing" | "completed" | "failed" | "cancelled";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_repositories_api_v1_repositories_get: {
        parameters: {
            query?: {
                /** @description 跳过的记录数 */
                skip?: number;
                /** @description 返回的记录数 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_repository_api_v1_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_api_v1_repositories__repository_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_repository_api_v1_repositories__repository_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_repository_api_v1_repositories__repository_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_analysis_api_v1_repositories__repository_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_v1_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_points_api_v1_knowledge_points_get: {
        parameters: {
            query: {
                /** @description 仓库 ID */
                repository_id: string;
                /** @description 分析版本号，不传则使用当前版本 */
                version?: string | null;
                /** @description 按分类筛选：DP-/AD-/AL-/ET-/DK- */
                category?: string | null;
                /** @description 按标签筛选 */
                tag?: string | null;
                /** @description 页码 */
                page?: number;
                /** @description 每页数量 */
                page_size?: number;
                /** @description 排序字段：created_at/title/confidence */
                sort_by?: string;
                /** @description 排序方向 */
                sort_order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedKnowledgePoints"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_point_api_v1_knowledge_points__point_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                point_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePoint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_stats_api_v1_repositories__repository_id__knowledge_stats_get: {
        parameters: {
            query?: {
                /** @description 分析版本号，不传则使用当前版本 */
                version?: string | null;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_suggestions_api_v1_search_suggestions_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSuggestionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_repositories__repository_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_version_api_v1_repositories__repository_id__switch_version_post: {
        parameters: {
            query: {
                /** @description 目标版本号 */
                version: string;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_version_api_v1_repositories__repository_id__rollback_post: {
        parameters: {
            query: {
                /** @description 回滚目标版本 */
                version: string;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_v1_files_get: {
        parameters: {
            query: {
                /** @description 仓库 ID */
                repository_id: string;
                /** @description 页码 */
                page?: number;
                /** @description 每页数量 */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_file_api_v1_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_v1_files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_file_api_v1_files__file_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_api_v1_files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_files_by_hash_api_v1_files_by_hash__content_hash__get: {
        parameters: {
            query: {
                /** @description 仓库 ID */
                repository_id: string;
            };
            header?: never;
            path: {
                content_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ast_nodes_api_v1_ast_nodes_get: {
        parameters: {
            query?: {
                /** @description 文件 ID（按文件查询节点） */
                file_id?: string | null;
                /** @description 仓库 ID（按仓库查询节点） */
                repository_id?: string | null;
                /** @description 节点类型过滤 */
                node_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AstNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ast_node_api_v1_ast_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AstNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_call_edges_api_v1_call_edges_get: {
        parameters: {
            query?: {
                /** @description 文件 ID（按文件查询调用边） */
                file_id?: string | null;
                /** @description 仓库 ID（按仓库查询调用边） */
                repository_id?: string | null;
                /** @description 调用者节点类型过滤 */
                node_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallEdge"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_callees_api_v1_call_edges__node_id__callees_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_callers_api_v1_call_edges__node_id__callers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_chain_api_v1_call_edges__node_id__chain_get: {
        parameters: {
            query?: {
                /** @description 最大遍历深度 */
                max_depth?: number;
            };
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dependencies_api_v1_repositories__repository_id__dependencies_get: {
        parameters: {
            query?: {
                /** @description 按生态系统过滤（maven/npm/pip/go/cargo） */
                ecosystem?: string | null;
                /** @description 按作用域过滤（compile/dev/test/runtime/peer） */
                scope?: string | null;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalDependency"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_dependencies_api_v1_repositories__repository_id__dependencies_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_frameworks_api_v1_repositories__repository_id__frameworks_get: {
        parameters: {
            query?: {
                /** @description 按类别过滤（frontend/backend/database/messaging 等） */
                category?: string | null;
                /** @description 最低置信度阈值 */
                min_confidence?: number | null;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkPattern"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_frameworks_api_v1_repositories__repository_id__frameworks_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_routes_api_v1_repositories__repository_id__routes_get: {
        parameters: {
            query?: {
                /** @description 按 HTTP 方法过滤（GET/POST/PUT/DELETE 等） */
                http_method?: string | null;
                /** @description 按框架过滤（spring_boot/express/flask/fastapi 等） */
                framework?: string | null;
                /** @description 路径模式模糊匹配 */
                path_pattern?: string | null;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiRoute"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_routes_api_v1_repositories__repository_id__routes_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
